import 'package:rumo_red_app/core/constants/imports.dart';
import 'package:rumo_red_app/screens/premium_editions/watch_ad/watch_ad_screen.dart';

class PickEditionsContainer extends StatelessWidget {
  final String assetName, text;
  final int index;
  const PickEditionsContainer(
      {super.key,
      required this.assetName,
      required this.text,
      required this.index});

  @override
  Widget build(BuildContext context) {
    return Padding(
        padding: const EdgeInsets.all(18.0),
        child: InkWell(
          onTap: () {
            index == 1
                ? CustomSpinWheelDialog.spinWheelDialog(
                    context,
                    image1: "assets/images/minor-game.png",
                    image2: "assets/images/drinking-game.png",
                    title: "Select the game",
                    buttonTitle1: "Minors in\naudience",
                    buttonTitle2: "Drinking\nWheel",
                    onPressed2: () {},
                    onPressed1: () {
                      CustomShowDialog.shoeCustomDialog(
                        isImage: false,
                        context,
                        title: "How do you want to create your quiz?",
                        buttonTitle1: 'By yourself',
                        buttonTitle2: 'Auto-Generated',
                        onPressed1: () {
                          Get.to(
                            PinJoinScreen(
                              isJoinScreen: false,
                              isAutoGeneratedScreen: false,
                              isMinor: false,
                              isSpinWheelScreen: true,
                              isByYourself: true,
                            ),
                          )?.then(
                            (value) => Get.back(),
                          );
                        },
                        onPressed2: () {},
                      );
                    },
                  ).then(
                    (value) => Get.back(),
                  )
                : index < 6
                    ? CustomShowDialog.shoeCustomDialog(
                        isImage: false,
                        context,
                        title: "How do you want to create your quiz?",
                        buttonTitle1: 'By yourself',
                        buttonTitle2: 'Auto-Generated',
                        onPressed1: () {
                          Get.to(CreatQuizByYourselfScreen());
                        },
                        onPressed2: () {
                          Get.to(
                            CustomShowDialog.shoeCustomDialog(
                              isImage: false,
                              context,
                              title: "Is there any minor in your players?",
                              buttonTitle1: 'Yes',
                              buttonTitle2: 'No',
                              onPressed1: () {
                                Get.to(
                                  PinJoinScreen(
                                    isJoinScreen: false,
                                    isAutoGeneratedScreen: true,
                                    isMinor: true,
                                    isByYourself: false,
                                  ),
                                )?.then((value) => Get.back());
                              },
                              onPressed2: () {
                                CustomShowDialog.shoeCustomDialog(
                                  isImage: false,
                                  context,
                                  title: "Do you want to play drinking game?",
                                  buttonTitle1: "Yes",
                                  buttonTitle2: "No",
                                  onPressed1: () {
                                    Get.to(AutoDrinkingPin())
                                        ?.then((value) => Get.back());
                                  },
                                  onPressed2: () {
                                    Get.to(
                                      PinJoinScreen(
                                        isJoinScreen: false,
                                        isAutoGeneratedScreen: true,
                                        isMinor: false,
                                        isByYourself: false,
                                      ),
                                    )?.then((value) => Get.back());
                                  },
                                );
                              },
                            ),
                          )?.then((value) => Get.back());
                        },
                      )
                    : CustomShowDialog.shoeCustomDialog(
                        context,
                        title: "Rewards",
                        buttonTitle1: "Buy Subscription",
                        isImage: true,
                        image: "assets/images/giftbox.png",
                        onPressed2: () {},
                        onPressed1: () {
                          Get.to(
                            showDialog(
                              context: context,
                              builder: (context) {
                                return Padding(
                                  padding: const EdgeInsets.all(30.0),
                                  child: Container(
                                    width:
                                        MediaQuery.of(context).size.width * 0.8,
                                    height: MediaQuery.of(context).size.height *
                                        0.9,
                                    decoration: BoxDecoration(
                                      borderRadius: BorderRadius.circular(30),
                                    ),
                                    child: BuySubscriptionScreen(),
                                  ),
                                );
                              },
                            ).then(
                              (value) => Get.back(),
                            ),
                          );
                        },
                      );
          },
          child: InkWell(
            child: Stack(
              children: [
                Container(
                  width: MediaQuery.of(context).size.width * 0.36,
                  height: MediaQuery.of(context).size.height * 0.17,
                  decoration: BoxDecoration(
                    color: AppColors.textFiledColor,
                    borderRadius: const BorderRadius.all(
                      Radius.circular(22),
                    ),
                    image: DecorationImage(
                      colorFilter: index > 5
                          ? ColorFilter.mode(
                              Colors.black.withOpacity(0.5), BlendMode.dstATop)
                          : ColorFilter.mode(Colors.white.withOpacity(0.99),
                              BlendMode.dstATop),
                      image: AssetImage(assetName),
                    ),
                  ),
                  child: Align(
                    alignment: Alignment.bottomCenter,
                    child: Padding(
                      padding: const EdgeInsets.all(8.0),
                      child: Text(
                        text,
                        style: const TextStyle(
                            fontSize: 16,
                            fontWeight: FontWeight.w600,
                            color: AppColors.pickEditionTextColor),
                      ),
                    ),
                  ),
                ),
                Align(
                  alignment: Alignment.topRight,
                  child: index < 6
                      ? const SizedBox()
                      : Image.asset("assets/images/upgrade-icon.png"),
                ),
              ],
            ),
          ),
        ));
  }
}
