import 'package:rumo_red_app/core/constants/imports.dart';

class CreatQuizByYourselfPage2Controller extends GetxController {
  void goToNextScreen() {
    Get.to(
      () => PinJoinScreen(
        isJoinScreen: false,
        isAutoGeneratedScreen: false,
        isMinor: false,
        isSpinWheelScreen: false,
        isByYourself: true,
        isDrinkingGame: false,
        isWithoutMinorDrinking: false,
        isAutoParticipantsDrinking: false,
      ),
    );
    update();
  }
}
