import 'package:rumo_red_app/core/constants/imports.dart';

class HomeScreenController extends GetxController {
  void goTONextScreen() {
    Get.to(
      PinJoinScreen(
        isJoinScreen: true,
        isAutoGeneratedScreen: false,
        isMinor: false,
        isByYourself: false,
        isDrinkingGame: false,
        isWithoutMinorDrinking: false,
        isAutoParticipantsDrinking: false,
      ),
    );
  }
}
