import 'package:rumo_red_app/core/constants/imports.dart';

class AppImages {
  static SvgPicture logo = SvgPicture.asset("assets/images/logo11.svg");
  static SvgPicture spinWheelScreenImg =
      SvgPicture.asset("assets/images/s11.svg");
  static SvgPicture drinkingParticipants =
      SvgPicture.asset("assets/images/drink_participant.svg");
  static SvgPicture noMinorScreenImg =
      SvgPicture.asset("assets/images/no_minor.svg");
  static SvgPicture createButton =
      SvgPicture.asset('assets/images/create11.svg');
  static SvgPicture joinButton = SvgPicture.asset('assets/images/join11.svg');
  static SvgPicture homeScreenImage =
      SvgPicture.asset("assets/images/home11.svg");
  static SvgPicture profileGoNextArrowImage =
      SvgPicture.asset("assets/images/next.svg");
  static SvgPicture spinWheelImage = SvgPicture.asset("assets/images/s11.svg");
  static SvgPicture createParticipantsImage =
      SvgPicture.asset("assets/images/quiz_par11.svg");
  static SvgPicture twoDrinksImage =
      SvgPicture.asset("assets/images/twodrinks11.svg");
  static SvgPicture textfieldImage =
      SvgPicture.asset("assets/images/text11.svg");
  static SvgPicture questionmarkTextFieldImage =
      SvgPicture.asset("assets/images/ques11.svg");
  static SvgPicture pinJoinImage =
      SvgPicture.asset("assets/images/pinjoin11.svg");
  static const AssetImage profileImage = AssetImage(
    "assets/images/frame.png",
  );
  static SvgPicture buySubscriptionDimondImage =
      SvgPicture.asset("assets/images/dimond1.svg");
  static SvgPicture paymentScreenImage =
      SvgPicture.asset("assets/images/payment.svg");
  static SvgPicture resultWinScreenImage =
      SvgPicture.asset("assets/images/win11.svg");
  static SvgPicture resultScreenImage =
      SvgPicture.asset("assets/images/result11.svg");
  static SvgPicture drinkingResultImage =
      SvgPicture.asset("assets/images/drinking11.svg");
  static Image getReadyScreenImage =
      Image.asset("assets/images/get-ready2.png");
  static SvgPicture autoGeneratedImage =
      SvgPicture.asset("assets/images/auto_generated11.svg");
  static Image profileHistoryImage = Image.asset(
    "assets/images/history3.png",
  );
  static Image profileAnalysisImage = Image.asset(
    "assets/images/analysis3.png",
  );
}
